spring:
  application:
    name: VendaServicosProdutos
  datasource:
    datasource:
      url: jdbc:mysql://servico-lan:3306/servico-lan
      username: edu
      password: 123456

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Formata as queries SQL para facilitar a leitura
server:
  port: 8080
