spring:
  application:
    name: VendaServicosProdutos

  datasource:
    url: jdbc:mysql://localhost:3306/services_lan
    username: root
    password: senha123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Formata as queries SQL para facilitar a leitura

  expiration: 5
  secret: "minha-chave-super-secreta-123456789123456789"
  emissor: "lanhouse"

server:
  port: 8080